### ISSUE TITLE
test_geolib_lrf.cpp compilation error with clang

### ISSUE THREAD

**Issue by Heuvendw** [tue-robotics/geolib2#15]
Clang will not compile the test_geolib_lrf.cpp file:

```cpp
/geolib2/test/test_geolib_lrf.cpp:107:29: error: variable length array of non-POD element type 'cv::Point' (aka 'Point_<int>')
    cv::Point rook_points[1][n_pts];
```
Problem is the dynamic size array part. It should either by dynamically created or another data structure should be used.

**Comment by MatthijsBurgh** [comment]
@Heuvendw, we are not using Clang and I am not familiar with Clang. So I suggest you to create a PR with a working solution. Then I will review that PR.

**Comment by MatthijsBurgh** [comment]
@Heuvendw, are you planning to create a PR yourself or suggest a solution? Otherwise I will be closing this issue.

**Comment by MatthijsBurgh** [comment]
No response from @Heuvendw so closing this issue.
