### ISSUE TITLE
Box::getMaxRadius incorrect if not centered around origin

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/geolib2#36]
https://github.com/tue-robotics/geolib2/blob/fee8a0b5dc6ff7641178aae6a11f250564e30709/src/Box.cpp#L76-L78

Should it give the radius relative to the origin or the center of the box?

**Comment by LoyVanBeek** [comment]
center, I'd say based on just how I would expect it as a user. But I'd also expect either have origin at a corner OR origin and center to line up.
In both cases, the max should be halved still, right?

**Comment by PetervDooren** [comment]
This function is correct I believe. It should give the radius to the origin.
The Max should not be halved as we are getting radius and not diameter.

**Comment by MatthijsBurgh** [comment]
Agreed
