### ISSUE TITLE
Add lrf unit tests for rendering.

### ISSUE THREAD

**Issue by PetervDooren** [tue-robotics/geolib2#73]
Possibly related to the bug encountered in https://github.com/tue-robotics/emc_simulator/issues/39
First step to debugging this is making tests for rendering lines and triangles making sure to test different line positions and orientations relative to the lrf.

**Comment by MatthijsBurgh** [comment]
You can already run `test_geolib` with a shape file (geo format and general mesh files). Otherwise you can change `test_geolib_lrf.cpp` to check various shapes. Maybe also with file loading.
